### ISSUE TITLE
Morning Session: Code Review

### ISSUE THREAD

**Issue by abiola-arobieke** [Maedea9/leaderboard-api#3]
Good job! 👍 👍. Your code is clean and easier to read. In my opinion,  it would be nice if you could declare the variable below locally since you are using it in just one function.

https://github.com/Maedea9/leaderboard-api/blob/1500859105bd95138981e96b3f858d7013d74e60/src/index.js#L4

**Comment by Maedea9** [comment]
Thanks for the suggestion @abiola-arobieke I already changed it 😄 
![change](https://user-images.githubusercontent.com/120128067/234898375-7ba42203-ac97-45e3-94ae-0bbe00c0f0c3.jpg)
